@api_HostAddress = https://api.ekoinv.com
### Login
POST {{api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "semih@gmail.com",
  "password": "Semih123"
}

### Get Active Session
GET {{api_HostAddress}}/api/auth/active-session
Accept: application/json
